In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/movies.csv")

In [3]:
df.head()

,movieId,title,genres
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
df.drop('movieId', axis=1, inplace=True)

In [10]:
df['genres'] = df['genres'].str.split('|').str[0]

In [11]:
df.head()

                                title     genres
0                          Toy Story   Adventure
1                      Jumanji (1995)  Adventure
2             Grumpier Old Men (1995)     Comedy
3            Waiting to Exhale (1995)     Comedy
4  Father of the Bride Part II (1995)     Comedy

In [12]:
df['title'] = df['title'].str.replace(r'\s*\(\d+\)', '')

<ipython-input-12-322efd35f537>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['title'] = df['title'].str.replace(r'\s*\(\d+\)', '')

In [13]:
df.head()

                         title     genres
0                   Toy Story   Adventure
1                      Jumanji  Adventure
2             Grumpier Old Men     Comedy
3            Waiting to Exhale     Comedy
4  Father of the Bride Part II     Comedy

In [14]:
df['title'] = df['title'].str.strip()
df['genres'] = df['genres'].str.strip()

In [15]:
df.head()

                         title     genres
0                    Toy Story  Adventure
1                      Jumanji  Adventure
2             Grumpier Old Men     Comedy
3            Waiting to Exhale     Comedy
4  Father of the Bride Part II     Comedy

In [16]:
df.to_csv('recommender.csv', index=False)

In [17]:
from google.colab import files
# download the CSV file
files.download('recommender.csv')

In [20]:
df = pd.read_csv("/content/recommender.csv")

In [21]:
df.head()

                         title     genres
0                    Toy Story  Adventure
1                      Jumanji  Adventure
2             Grumpier Old Men     Comedy
3            Waiting to Exhale     Comedy
4  Father of the Bride Part II     Comedy